spring:
  application:
    name: YunMail
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  mvc:
    pathmatch:
       matching-strategy: ant_path_matcher
  profiles:
    active: dev
    include:
      - swagger
      - quartz
      - druid
knife4j:
  enable: true
  setting:
    language: zh-CN