spring:
  application:
    name: YunMail
  mvc:
    pathmatch:
       matching-strategy: ant_path_matcher
  profiles:
    active: dev
    include: swagger
knife4j:
  enable: true
  setting:
    language: zh-CN