spring:
  application:
    name: YunMail
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #主要数据源
    primary:
      url: jdbc:mysql://127.0.0.1:3306/yun?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    #备用数据源
    standby:
      url: jdbc:mysql://127.0.0.1:3306/yun?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    #Task数据源
    task:
      url: jdbc:mysql://127.0.0.1:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
    include:
      - swagger
      - quartz
      - druid
      - mq
knife4j:
  enable: true
  setting:
    language: zh-CN