spring:
  application:
    name: YunMail
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
    include:
      - swagger
      - quartz
      - druid
      - mq
      - sms
      - oauth
      - datasource
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: yun
      use-key-prefix: true
      # 防止缓存穿透
      cache-null-values: true
  mail:
    host: smtp.feishu.cn
    username: timestore@totime.cn
    password: lG5jjKUFKTjiBpIy
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  freemarker:
    cache: false
    # 模板路径
    template-loader-path: classpath:/templates
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    # 通用模板文件路径
    general-base-package-path: /templates/general
    # 邮件模板文件路径
    mail-base-package-path: /templates/email/
knife4j:
  enable: true
  setting:
    language: zh-CN
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl