server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yun?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    request-context-attribute: request
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
  data:
    mongodb:
      uri: mongodb://JanYork:[密码]@121.62.00.121:27017/yun?authSource=admin
sa-token:
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-64
  is-log: false
  is-print: off
  isReadCookie: false
  token-name: token
  token-session-check-login: false
mybatis-plus:
  global-config.banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework: error
    net.totime.mail: info
    com.xxl.job: error
alibaba:
  cloud:
    access-key: cswanijlfbweigf4w
    secret-key: wF0IcW6Y2BtEmhk5Ult424124lahtGWy38Id
xxl:
  job:
    admin:
      addresses: http://121.62.61.000:8008/xxl-job-admin
    accessToken: default_token
    executor:
      appname: yun-job
      ip: 127.0.0.1
      port: 8086
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      # noinspection SpringBootApplicationYaml
      address:
knife4j:
  enable: true
swagger:
  # 是否开启swagger
  enable: true
  title: "云寄2.0版本服务端"
  description: "一站式时光信件服务平台"
  version: "2.0.0"
  contact:
    name: "JanYork"
    url: "https://totime.net"
    email: "747945307@qq.com"
pay:
  wx:
    appId: 1111111111
    mchId: 11111111
    apiKey: 111111111111111
    inputCharset: utf-8
    #    notifyUrl: https://api.totime.net/weixin/pay/notify
    #    returnUrl: https://api.totime.net/weixin/pay/notify
    notifyUrl: http://w59fe5.natappfree.cc/pay/wx/callback
    returnUrl: http://w59fe5.natappfree.cc/pay/wx/callback
    apiClientKeyP12: C:\Users\JanYork\Desktop\YunMailServer\src\main\resources\apiclient_cert.p12
    # 开启轮询
    enablePoll: true
  ali:
    app-id: 1111111111
    pid: 1111111111
    seller: 11111111111
    inputCharset: utf-8
    #    notifyUrl: https://api.totime.net/ali/pay/notify
    #    returnUrl: https://api.totime.net/ali/pay/notify
    notifyUrl: http://w59fe5.natappfree.cc/pay/ali/callback
    returnUrl: http://w59fe5.natappfree.cc/pay/ali/callback
    keyPublicPath: C:\Users\JanYork\Desktop\YunMailServer\src\main\resources\keyPublic.txt
    keyPrivatePath: C:\Users\JanYork\Desktop\YunMailServer\src\main\resources\keyPrivate.txt
    # 开启轮询
    enablePoll: true
justauth:
  enabled: true
  type:
    ALIPAY:
      client-id: 1111111111
      client-secret: 111111111
      redirect-uri: https://api.totime.net/oauth/alipay/callback
      alipay-public-key: 1111111111111111
    GITEE:
      client-id: 111111111111
      client-secret: 1111111111111
      redirect-uri: http://127.0.0.1:8080/oauth/gitee/callback
    GITHUB:
      client-id: 11111111111
      client-secret: 11111111111
      redirect-uri: http://127.0.0.1:8080/oauth/github/callback
    DOUYIN:
      client-id: 1111111111
      client-secret: 111111111111
      redirect-uri: https://api.totime.net/oauth/douyin/callback
  cache:
    prefix: auth_
    type: redis
wx:
  miniapp:
    appid: 111111111
    secret: 11111111111
    msg-data-format: JSON
    config-storage:
      type: RedisTemplate
      keyPrefix: wx-mini
      redis:
        host: 127.0.0.1
        port: 6379
        database: 1
  mp:
    appid: 11111111
    secret: 111111111111
    token: 1111111111
    aesKey: 111111111
    config-storage:
      type: RedisTemplate
      keyPrefix: wx-mp
      redis:
        host: 127.0.0.1
        port: 6379
        database: 1
tencent:
  cos:
    secret-id: 111
    secret-key: 1111
    region: ap-guangzhou
    bucket: 111111111
    url: https://111111111
  sms:
    secret-id: 111111111111
    secret-key: 11111111111
    region: ap-beijing
third:
  app-code: 1111111111
  three-element:
    url: https://mobile3elements.shumaidata.com/mobile/verify_real_name
  two-element:
    url: https://zid.market.alicloudapi.com/idcheck/Post
  logistics:
    url: https://wuliu.market.alicloudapi.com/kdi
ws:
  allowed-origins: http://localhost:3000
  endpoint: /ws
  pay: /third/pay
kdzs:
  key: 1111111111
  secret: 11111111111111
baidu:
  ai:
    app-id: 111111111
    api-key: 11111111111
    secret-key: 11111111111111
