spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: prod
  #    include: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.feishu.cn
    username: yunji@totime.net
    password: 1111111111111
    defaultEncoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            required: true
system:
  wx-mp-name: "云寄时光机"
  wx: "JanYork"
  # 400 电话
  phone: "848-1124"
  # 运营手机号
  operator-phone: "000000"
  # 系统开发者手机号
  developer-phone: "000000"
