# SMS控制台: https://dysms.console.aliyun.com
server:
  port: 8080
## 控制台: https://ons.console.aliyun.com
## Spring Cloud Alibaba RocketMQ 文档：https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-docs/src/main/asciidoc-zh/rocketmq.adoc
## RocketMQ 帮助文档：https://help.aliyun.com/product/29530.html
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yun?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
sa-token:
  token-name: yun
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-64
  is-log: false
  is-print: off
mybatis-plus:
  global-config.banner: false
logging:
  level:
    org.springframework: error
    net.totime.mail: error