# SMS控制台: https://dysms.console.aliyun.com
server:
  port: 8080
## 控制台: https://ons.console.aliyun.com
## Spring Cloud Alibaba RocketMQ 文档：https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-docs/src/main/asciidoc-zh/rocketmq.adoc
## RocketMQ 帮助文档：https://help.aliyun.com/product/29530.html
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yun?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
sa-token:
  token-name: yun
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-64
  is-log: true