# PHP环境 -> 一键安装
version: '3.7'
services:
    php7.4:
        image: php:7.4-fpm
        container_name: php7.4
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./7.4/php/conf.d:/usr/local/etc/php/conf.d
            - ./7.4/php/logs:/var/log/php
            - ./www:/var/www
        command: tail -f /dev/null
    php8.0:
        image: php:8.0-fpm
        container_name: php8.0
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./php/conf.d:/usr/local/etc/php/conf.d
            - ./php/logs:/var/log/php
            - ./www:/var/www
        command: tail -f /dev/null