# 基于Java8基础镜像
FROM java:8
# 指定作者
MAINTAINER JanYork
# 创建日志目录和应用目录
RUN mkdir -p /log
RUN mkdir -p /app
# 指定工作目录
WORKDIR /app
# 拷贝当前目录下的app.jar到镜像中
COPY app-*.jar app/app.jar
# 暴露端口
EXPOSE 8099

ENV JAVA_OPTS=""
ENTRYPOINT ["java $JAVA_OPTS -jar /app/app.jar"]