swagger:
  # 是否开启swagger
  enable: true
  title: "云寄服务端接口文档"
  description: "与时同行旗下云寄时光驿站服务"
  license: "Apache License Version 2.0"
  licenseUrl: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "2.0.0"
  contact:
    name: "JanYork"
    url: "https://mail.totime.cn"
    email: "747945307@qq.com"