justauth:
    domain: http://localhost:8088
    enabled: true
    type:
      GITEE:
        client-id: 创建成功的应用的id
        client-secret: 创建成功的应用的密钥
        redirect-uri: ${justauth.domain}/oauth/gitee/callback
      GITHUB:
        client-id: 创建成功的应用的id
        client-secret: 创建成功的应用的密钥
        redirect-uri: ${justauth.domain}/oauth/github/callback
      QQ:
        client-id: 创建成功的应用的id
        client-secret: 创建成功的应用的密钥
        redirect-uri: ${justauth.domain}/oauth/qq/callback
      DOUYIN:
        client-id: 创建成功的应用的id
        client-secret: 创建成功的应用的密钥
        redirect-uri: ${justauth.domain}/oauth/douyin/callback
      ALIPAY:
        client-id: 创建成功的应用的id
        client-secret: 创建成功的应用的密钥
        redirect-uri: ${justauth.domain}/oauth/alipay/callback
      WECHAT_MP:
        client-id: 创建成功的应用的id
        client-secret: 创建成功的应用的密钥
        redirect-uri: ${justauth.domain}/oauth/wechat_mp/callback
      WECHAT_OPEN:
        client-id: 创建成功的应用的id
        client-secret: 创建成功的应用的密钥
        redirect-uri: ${justauth.domain}/oauth/wechat_open/callback